### ISSUE TITLE
Dirty water gives 100% available performance in Steam engines

### ISSUE THREAD

**Issue by bumbasher** [Dysoch/DyTech#330]
Primary Steam Engine Mk I have 100% available performance when powered with dirty water with 100 degree temperature.

In previous versions it only gave like 80% (?) performance with dirty water.

Mods used:
AdvancedEquipment_0.4.0.zip
CORE-DyTech-Core_1.2.0.zip
craftfaster_0.0.3.zip
DefaultRequestAmount_1.0.0.zip
Fluid Void_1.0.1.zip
Landfill_2.1.5.zip
MAIN-DyTech-Machine_1.1.0.zip
MAIN-DyTech-Power_1.1.0.zip
MAIN-DyTech-War_1.1.0.zip
Treefarm-Lite_0.2.0.zip
UraniumPower_0.6.2.zip

**Comment by MagicLegend** [comment]
Whoops. (Sortof) my fault. Dysoch changed the dirty / clean water to make uraniumpower compatible. Will be on my to-do list for tomorrow. Thank you for reporting. I'll close the issue once I've committed an fix.

**Comment by Skillabstinenz** [comment]
it's not a bug it's a feature :-P

**Comment by Timeslice42** [comment]
This is still an issue. In the mean time I just set the max temperature of (dirty) water to 80 instead of 100.

**Comment by MagicLegend** [comment]
It is. School has started here, so I have less time to work on free-time projects like Dytech :-).

I'll look into fixing this soon-ish

**Comment by Timeslice42** [comment]
Thanks :)
